### ISSUE TITLE
Script fails with error parsing token on firewall main page

### ISSUE THREAD

**Issue by useribs** [sysadminbr/migrate_pfsense#1]
Hola!

I've been trying to use the script with OPNsense 24.7.7-amd64, done all the steps as per README and getting the following error:

```
/migrate_pfsense/src# python3 migrate_pfsense.py
connecting to firewall on https://192.168.8.x
[+] firewall login sucessful
==== STARTING MIGRATION OF STATIC ROUTES
==== STARTING MIGRATION OF CERTIFICATES
error parsing token on firewall main page

```

I've pinpointed it that at the failing call r.text there are no "hidden" values with CSRF, instead it's being passed as JavaScript:

xhr.setRequestHeader("X-CSRFToken", "O0r5HWqHwRocQMk40fFHyg" );

After investigation it seems that system_camanager.php and subsequent links are missing from modern OPNsense, it's been replaced with /ui/trust/cert

**Comment by useribs** [comment]
What was the version of OPNsense that migration script was known to work with?

**Comment by tjakobi** [comment]
Having exactly the same issue using OPNsense 24.7.7-amd64 freshly installed.

**Comment by sysadminbr** [comment]
It has been used in opnsense 23.x. 
not updated yet for 24.x series.

**Comment by tjakobi** [comment]
Thank you for your reply.

I just took my chances and downloaded the 23.x series release, did a fresh install, imported everything and was able to update up to 24.7, took a bit longer but worked flawlessly.

Thank you for your work!

**Comment by sudheeshb** [comment]
@sysadminbr  Is there any plan to update the tool for 24.7?

**Comment by sysadminbr** [comment]
Updated to work with 24.7.7.

**Comment by sysadminbr** [comment]
closing it since it was updated to work on most recent 24.7 opnsense series.
